//! Typed message payloads, encoded as tagged fields (see `fields.rs`).
//!
//! Every struct mirrors `ext/go/pxb` one-to-one so the two SDKs interop at
//! the byte level. Encode field order matches Go's writers — golden tests in
//! `tests/pxb_test.rs` pin the bytes against `ext/go/pxb/testdata/*.bin`.
//!
//! All messages are generated by the [`pxb_message!`] macro, which produces
//! the struct, `encode()`, and `decode()` from a single declaration.

use super::codec::Error;
use super::fields::{walk_fields, FieldWriter};
use super::wire::WireField;

pxb_message! {
    /// The first frame from an extension.
    pub struct Hello {
        1 => name: String,
        2 => version: String,
        3 => caps: u32,
        4 => protocol: u16,
    }
}

pxb_message! {
    /// The host reply to `Hello`.
    pub struct HelloAck {
        1 => protocol: u16,
        2 => phi_version: String,
        3 => cwd: String,
        4 => session_id: String,
        5 => extension_dir: String,
    }
}

pxb_message! {
    /// Registers a slash command.
    pub struct RegisterCommand {
        1 => name: String,
        2 => description: String,
        /// Host leaves `/name ` in the composer on picker accept / bare submit.
        /// `false` omits the wire field (backward compatible).
        option 3 => needs_args: bool,
    }
}

pxb_message! {
    /// Registers an LLM tool; `schema_json` is opaque JSON Schema bytes.
    pub struct RegisterTool {
        1 => name: String,
        2 => description: String,
        3 => schema_json: Vec<u8>,
        /// Host RPC wait for this tool's result, in seconds. `0` omits the field
        /// (host default). Host clamps to a maximum.
        option 4 => timeout_sec: u32,
        /// Extension can answer detail-from-args requests.
        /// `false` omits the wire field (backward compatible).
        option 5 => has_detail: bool,
        /// Side-effect-free; the host may batch read-only calls concurrently.
        /// `false` omits the wire field (old hosts stay sequential).
        option 6 => readable: bool,
    }
}

pxb_message! {
    /// Ext→host reply for a detail-from-args request (body of tool invoke is reused).
    pub struct ToolDetailResult {
        1 => detail: String,
    }
}

pxb_message! {
    /// Declares event / intercept interests.
    pub struct Subscribe {
        1 => events: Vec<u16>,
        2 => intercept: Vec<u16>,
    }
}

pxb_message! {
    /// Host→ext when the user runs a slash command.
    pub struct CommandInvoked {
        1 => name: String,
        2 => args: String,
    }
}

pxb_message! {
    /// Ext→host slash command outcome.
    pub struct CommandResponse {
        1 => ok: bool,
        2 => error: String,
        3 => notify: String,
        4 => submit: String,
    }
}

pxb_message! {
    /// Host→ext for a registered tool.
    pub struct ToolInvoke {
        1 => name: String,
        2 => args: Vec<u8>,
    }
}

pxb_message! {
    /// Ext→host tool outcome.
    pub struct ToolResultMsg {
        1 => content: String,
        2 => detail: String,
        3 => output: String,
        4 => is_error: bool,
        5 => error: String,
        /// TUI tool row starts expanded (user toggle still wins).
        option 6 => expanded: bool,
    }
}

pxb_message! {
    /// Host→ext for a blocking decision point.
    pub struct InterceptReq {
        1  => event: u16,
        2  => tool_name: String,
        3  => tool_call_id: String,
        4  => input: Vec<u8>,
        5  => content: String,
        6  => is_error: bool,
        7  => err_text: String,
        8  => prompt: String,
        9  => reason: String,
        10 => target_id: String,
        11 => turn_index: u32,
    }
}

pxb_message! {
    /// Ext→host intercept reply.
    pub struct InterceptResp {
        1  => block: bool,
        2  => stop: bool,
        3  => cancel: bool,
        4  => reason: String,
        5  => input: Vec<u8>,
        6  => content: String,
        7  => context: String,
        8  => system_prompt_append: String,
        9  => toast: String,
        10 => handled: bool,
        11 => prompt: String,
        12 => continue_: bool,
    }
}

pxb_message! {
    /// Fire-and-forget host→ext lifecycle event.
    pub struct EventNotify {
        1  => event: u16,
        2  => tool_name: String,
        3  => tool_call_id: String,
        4  => input: Vec<u8>,
        5  => is_error: bool,
        6  => prompt: String,
        7  => reason: String,
        8  => turn_index: u32,
        9  => session_id: String,
        10 => previous_session_id: String,
        11 => target_session_id: String,
    }
}

pxb_message! {
    /// Ext→host UI toast / footer status.
    pub struct NotifyMsg {
        1 => level: String,
        2 => message: String,
        3 => status: String,
        4 => status_set: bool,
    }
}

pxb_message! {
    /// Ext→host capability RPC.
    pub struct HostRequest {
        1 => method: String,
        2 => arg: String,
    }
}

pxb_message! {
    /// Host→ext reply to a `HostRequest`.
    pub struct HostResult {
        1 => ok: bool,
        2 => error: String,
        3 => body: String,
    }
}

pxb_message! {
    /// Host→ext session identity push.
    pub struct SessionMeta {
        1 => session_id: String,
        2 => cwd: String,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Round-trip every message through encode→decode→encode and verify
    /// determinism (same struct, same bytes).
    #[test]
    fn all_messages_roundtrip() {
        macro_rules! rt {
            ($ty:ident, $expr:expr) => {{
                let bytes = ($expr).encode();
                let decoded = $ty::decode(&bytes).unwrap();
                assert_eq!(decoded.encode(), bytes);
            }};
        }

        rt!(
            Hello,
            Hello {
                name: "greet".into(),
                version: "1.0.0".into(),
                caps: 3,
                protocol: 1,
            }
        );
        rt!(
            HelloAck,
            HelloAck {
                protocol: 1,
                phi_version: "v0.19.0".into(),
                cwd: "/tmp".into(),
                session_id: "s1".into(),
                extension_dir: "/ext".into(),
            }
        );
        rt!(
            RegisterCommand,
            RegisterCommand {
                name: "hi".into(),
                description: "Say hi".into(),
                needs_args: true,
            }
        );
        rt!(
            RegisterTool,
            RegisterTool {
                name: "t".into(),
                description: "d".into(),
                schema_json: br#"{"type":"object"}"#.to_vec(),
                timeout_sec: 120,
                has_detail: true,
                readable: true,
            }
        );
        rt!(
            ToolDetailResult,
            ToolDetailResult {
                detail: "path/to/file".into(),
            }
        );
        rt!(
            Subscribe,
            Subscribe {
                events: vec![5, 10],
                intercept: vec![1, 2],
            }
        );
        rt!(
            CommandInvoked,
            CommandInvoked {
                name: "hi".into(),
                args: "a b".into(),
            }
        );
        rt!(
            CommandResponse,
            CommandResponse {
                ok: false,
                error: "boom".into(),
                notify: String::new(),
                submit: "next".into(),
            }
        );
        rt!(
            ToolInvoke,
            ToolInvoke {
                name: "t".into(),
                args: br#"{"k":1}"#.to_vec(),
            }
        );
        rt!(
            ToolResultMsg,
            ToolResultMsg {
                content: "c".into(),
                detail: "d".into(),
                output: "o".into(),
                is_error: true,
                error: "e".into(),
                expanded: true,
            }
        );
        rt!(
            InterceptReq,
            InterceptReq {
                event: 1,
                tool_name: "bash".into(),
                tool_call_id: "c1".into(),
                input: br#"{"command":"ls"}"#.to_vec(),
                content: "out".into(),
                is_error: false,
                err_text: String::new(),
                prompt: "p".into(),
                reason: "r".into(),
                target_id: "t2".into(),
                turn_index: 3,
            }
        );
        rt!(
            InterceptResp,
            InterceptResp {
                block: true,
                stop: false,
                cancel: false,
                handled: true,
                continue_: true,
                reason: "r".into(),
                input: b"in".to_vec(),
                content: "c".into(),
                context: "ctx".into(),
                system_prompt_append: "sys".into(),
                toast: "t".into(),
                prompt: "p".into(),
            }
        );
        rt!(
            EventNotify,
            EventNotify {
                event: 5,
                tool_name: "t".into(),
                tool_call_id: "c".into(),
                input: b"i".to_vec(),
                is_error: true,
                prompt: "p".into(),
                reason: "r".into(),
                turn_index: 2,
                session_id: "s".into(),
                previous_session_id: "ps".into(),
                target_session_id: "ts".into(),
            }
        );
        rt!(
            NotifyMsg,
            NotifyMsg {
                level: "info".into(),
                message: "Hello".into(),
                status: "st".into(),
                status_set: true,
            }
        );
        rt!(
            HostRequest,
            HostRequest {
                method: "confirm".into(),
                arg: r#"{"Title":"t"}"#.into(),
            }
        );
        rt!(
            HostResult,
            HostResult {
                ok: true,
                error: String::new(),
                body: "b".into(),
            }
        );
        rt!(
            SessionMeta,
            SessionMeta {
                session_id: "s2".into(),
                cwd: "/x".into(),
            }
        );
    }

    #[test]
    fn decode_skips_unknown_tags() {
        let mut w = FieldWriter::new();
        w.put_string(1, "name");
        w.put_string(200, "future field"); // experimental, must be skippable
        w.put_string(2, "1.0.0");
        let h = Hello::decode(&w.into_vec()).unwrap();
        assert_eq!(h.name, "name");
        assert_eq!(h.version, "1.0.0");
    }
}
